name: Release preaparation

on:
  push:
    tags:
    - '*'
    
permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ vars.GITHUB_REF_NAME }}
        skipIfReleaseExists: true
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: "./cmd/kndp"
        binary_name: "kndp"
        ldflags: -X "globals.Version=${{ env.APP_VERSION }}"